<center><img src='https://raw.githubusercontent.com/Jangrae/img/master/title.png' width=500/></center>

<center><img src='https://raw.githubusercontent.com/Jangrae/img/master/practice.png' width=300/></center>

# 실습 #1: print 함수

1) 숫자 123456을 출력하세요.

2) 숫자 123, 456을 각각의 print 함수로 출력하세요.

3) 숫자 123, 456을 하나의 print 함수로 출력하세요.

4) 문자열 '파이썬을 배웁시다.', '누구든 할 수 있습니다.'를 각각의 print 함수로 출력하세요.

5) 문자열 '파이썬을 배웁시다.',  '누구든 할 수 있습니다.'를 하나의 print 함수로 출력하세요.

6) 숫자 123, 문자열 '오늘은', 문자열 '12월20일 입니다.'를 각각의 print 함수로 출력하세요.

7) 숫자 123, 문자열 '오늘은', 문자열 '12월20일 입니다.'를 하나의 print 함수로 출력하세요.

# 실습 #2: 숫자 다루기

1) 두 수 125, 5를 더하고, 빼고, 곱하고, 나눠 보세요.

2) 178을 13으로 나눴을 때 몫을 구하세요.

3) 3854를 11로 나눴을 때 몫을 구하세요.

4) 178을 13으로 나눴을 때 나머지를 구하세요.

5) 3854를 11로 나눴을 때 나머지를 구하세요.

6) 563421이 3의 배수인지 확인해 보세요.

7) 2의 10제곱을 구하세요.

8) 6의 -3제곱을 구하시오.

9) 652가 87보다 큰 지를 비교 연산자로 확인하세요.

10) 31과 31.0이 같은 지를 비교 연산자로 확인하세요.

11) 24와 24.0이 다른 지를 비교 연산자로 확인하세요.

# 실습 #3: 변수 다루기

1) 변수 v1에 48, 변수 v2에 '홍길동'을 저장하고 각각 출력하세요.

2) 변수 a, b에 임의의 숫자를 각각 저장하고 a와 b를 곱하여 출력하세요.

3) 변수 a, b에 임의의 숫자를 각각 저장하고 변수 c에 a와 b의 합, 변수 d에 a와 b의 곱을 저장하여 크기를 비교하세요.

4) 변수 g에 1을 저장하고 g에 1을 더해서 다시 g에 대입하세요.

5) 변수 h에 2를 저장하고 h에 2를 곱해서 다시 h에 대입하세요.

6) 변수 i에 6을 저장하고 i의 2제곱을 다시 i에 대입하세요.

7) [심화] 홍길동의 과목별 점수는 아래와 같습니다.
- 국어: 96점, 수학: 72점, 영어: 88점
- 변수 kor, math, eng에 각 과목 점수를 저장한 뒤,
- 변수 avg에 변수를 이용한 연산으로 계산한 평균 점수를 저장하여
- 문자열 '홍길동의 평균 점수는'과 avg를 하나의 print 함수로 출력하세요.
- 평균 = (전체 자료의 합) / (전체 자료의 수)