### Daum Exchange
- `https://finance.daum.net`

In [1]:
import pandas as pd
import requests

In [2]:
url = 'https://finance.daum.net/api/exchanges/summaries'

In [3]:
response = requests.get(url)
response

In [4]:
headers = {'User-Agent':'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36',
          'Referer': 'https://finance.daum.net/exchanges'}

In [5]:
response = requests.get(url, headers=headers)
response

In [10]:
#response.json()
#response.json()['data'][0]
data = response.json()['data']

{'symbolCode': 'FRX.KRWUSD',
 'date': '2024-03-19 19:42:08',
 'currencyCode': 'USD',
 'currencyName': '달러',
 'currencyUnit': 1,
 'country': '미국',
 'region': {'korName': '아메리카', 'engName': 'America'},
 'name': '미국 (USD/KRW)',
 'recurrenceCount': 283,
 'basePrice': 1338.5,
 'change': 'RISE',
 'changePrice': 2.0,
 'changeRate': 0.0014964459,
 'cashBuyingPrice': 1361.92,
 'cashSellingPrice': 1315.08,
 'ttBuyingPrice': 1325.4,
 'ttSellingPrice': 1351.6,
 'tcBuyingPrice': None,
 'fcSellingPrice': None,
 'exchangeCommission': 7.1788,
 'usDollarRate': 1.0,
 'chartImageUrl': {'day': 'https://t1.daumcdn.net/finance/chart/kr/daumforex/d/FRX.KRWUSD.png',
  'month': 'https://t1.daumcdn.net/finance/chart/kr/daumforex/m/FRX.KRWUSD.png',
  'month3': 'https://t1.daumcdn.net/finance/chart/kr/daumforex/m3/FRX.KRWUSD.png',
  'year': 'https://t1.daumcdn.net/finance/chart/kr/daumforex/y/FRX.KRWUSD.png'}}

In [12]:
df = pd.DataFrame(data)[['country', 'currencyName', 'basePrice']]

In [13]:
df

   country currencyName  basePrice
0       미국           달러    1338.50
1       일본            엔     889.16
2       중국           위안     185.62
3       유로           유로    1451.67
4       영국          파운드    1697.69
5      스위스           프랑    1505.79
6      캐나다           달러     986.15
7     뉴질랜드           달러     809.12
8       홍콩           달러     171.12
9      브라질           레알     266.06
10     멕시코           페소      79.24
11  아랍에미리트          디르함     364.48
12    쿠웨이트          디나르    4352.00
13     바레인          디나르    3550.87
14      인도           루피      16.12
15     사우디           리얄     356.90
16    노르웨이          크로네     125.09
17     덴마크          크로나     194.67
18   말레이시아          링키트     282.80
19   방글라데시           타카      12.20
20    파키스탄           루피       4.80
21   인도네시아          루피아       8.54
22      대만           달러      42.07
23     필리핀           페소      23.94
24     스웨덴          크로나     127.74
25      호주           달러     871.77
26    싱가포르           달러     996.83
27      태국           바트      37.10
28     이집트          파운드      28.38
29    브루나이           달러     996.83
30    이스라엘          쉐캐림     365.06
31     요르단          디나르    1887.87
32     베트남            동       5.41
33     러시아           루블      14.46
34     헝가리          포린트       3.67
35     폴란드          줄러티     335.76
36     남아공           랜드      70.58
37      몽골          투그릭       0.39
38      체코          코루나      57.53
39   카자흐스탄           텡게       2.97
40     카타르           리얄     367.01
41    튀르키예           리라      41.39